# ai-gen (ChatGPT-4, 2)
# Edited example from our labs; used ChatGPT to refine it for our project
name: CI Workflow  # Name of the workflow

on:
  push:
    branches: [master]
    paths:  # Only runs when these files are changed
      - 'website/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/test-coverage.yml'  # Always rerun if you change the workflow itself
  pull_request:
    branches: [master]
    paths:
      - 'website/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/test-coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Ensure consistency in Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r website/server/requirements.txt

      - name: Run Tests with Pytest
        run: PYTHONPATH=. pytest --cov=website --cov-report=term-missing tests/
        # Other directories w/ python files (excluding chart-scripts): --cov=Eulogy-Quest/GPT --cov=Eulogy-Quest/triggers
